/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.userInterfacePatientAdmin;

/**
 *
 * @author ajitpatil
 */
public class PatientAdminJFrame extends javax.swing.JFrame {

    /**
     * Creates new form PatientAdminJFrame
     */
    public PatientAdminJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane = new javax.swing.JSplitPane();
        patientAdminLeftJPanel = new javax.swing.JPanel();
        patientRegBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        patManageBtn = new javax.swing.JButton();
        patientAdminRightJPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        patientRegBtn.setText("Patient Registration");

        logoutBtn.setText("Logout");

        patManageBtn.setText("Patient Manager");
        patManageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patManageBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout patientAdminLeftJPanelLayout = new javax.swing.GroupLayout(patientAdminLeftJPanel);
        patientAdminLeftJPanel.setLayout(patientAdminLeftJPanelLayout);
        patientAdminLeftJPanelLayout.setHorizontalGroup(
            patientAdminLeftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientAdminLeftJPanelLayout.createSequentialGroup()
                .addComponent(patientRegBtn)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(patientAdminLeftJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoutBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(patManageBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        patientAdminLeftJPanelLayout.setVerticalGroup(
            patientAdminLeftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientAdminLeftJPanelLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(patientRegBtn)
                .addGap(183, 183, 183)
                .addComponent(patManageBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 242, Short.MAX_VALUE)
                .addComponent(logoutBtn)
                .addGap(90, 90, 90))
        );

        jSplitPane.setLeftComponent(patientAdminLeftJPanel);

        javax.swing.GroupLayout patientAdminRightJPanelLayout = new javax.swing.GroupLayout(patientAdminRightJPanel);
        patientAdminRightJPanel.setLayout(patientAdminRightJPanelLayout);
        patientAdminRightJPanelLayout.setHorizontalGroup(
            patientAdminRightJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1043, Short.MAX_VALUE)
        );
        patientAdminRightJPanelLayout.setVerticalGroup(
            patientAdminRightJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 699, Short.MAX_VALUE)
        );

        jSplitPane.setRightComponent(patientAdminRightJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1165, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void patManageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patManageBtnActionPerformed
      PatientManager PatientManager = new PatientManager();
       jSplitPane.setRightComponent(PatientManager);


        // TODO add your handling code here:
    }//GEN-LAST:event_patManageBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientAdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientAdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientAdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientAdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientAdminJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane jSplitPane;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton patManageBtn;
    private javax.swing.JPanel patientAdminLeftJPanel;
    private javax.swing.JPanel patientAdminRightJPanel;
    private javax.swing.JButton patientRegBtn;
    // End of variables declaration//GEN-END:variables
}
