/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.patientEnterPriseAdmin;
//import com.view.SignUp;

import com.view.PatiendRegistration;
import org.springframework.context.ApplicationContext;
import org.springframework.stereotype.Controller;

/**
 *
 * @author ajitpatil
 */
@Controller(value = "PatientEnterpriseAdminJFrame")
public class PatientEnterpriseAdminJFrame extends javax.swing.JFrame {

    PatiendRegistration patiendRegistration;
    PatientManagerJPanel managerJPanel;
    PatientAdminReg patientAdminReg;

    /**
     * Creates new form PatientEnterpriseAdminJFrame
     */
    public PatientEnterpriseAdminJFrame(PatiendRegistration patiendRegistration,
            PatientManagerJPanel managerJPanel,
            PatientAdminReg patientAdminReg, ApplicationContext applicationContext) {
        this.patiendRegistration = applicationContext.getBean(PatiendRegistration.class);
        this.managerJPanel = applicationContext.getBean(PatientManagerJPanel.class);
        this.patientAdminReg = applicationContext.getBean(PatientAdminReg.class);

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        patientAdminLeftJPanel = new javax.swing.JPanel();
        patientRegBtn = new javax.swing.JButton();
        patientMangBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        panelMain = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        patientAdminLeftJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        patientRegBtn.setText("Patient Registration");
        patientRegBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientRegBtnActionPerformed(evt);
            }
        });
        patientAdminLeftJPanel.add(patientRegBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        patientMangBtn.setText("Patient Manager");
        patientMangBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientMangBtnActionPerformed(evt);
            }
        });
        patientAdminLeftJPanel.add(patientMangBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 276, -1, -1));

        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        patientAdminLeftJPanel.add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 421, -1, -1));

        jSplitPane1.setLeftComponent(patientAdminLeftJPanel);

        panelMain.setMaximumSize(new java.awt.Dimension(1068, 719));
        panelMain.setMinimumSize(new java.awt.Dimension(1068, 719));

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1068, Short.MAX_VALUE)
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 719, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(panelMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void patientRegBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientRegBtnActionPerformed
        patiendRegistration.setVisible(true);

    }//GEN-LAST:event_patientRegBtnActionPerformed

    private void patientMangBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientMangBtnActionPerformed
        panelMain.removeAll();
        managerJPanel.setSize(panelMain.getSize());
        panelMain.add(managerJPanel);
        panelMain.repaint();
        panelMain.revalidate();        // TODO add your handling code here:

    }//GEN-LAST:event_patientMangBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        /* SignUp signUp = new SignUp();
        setVisible(signUp);
        dispose();*/
this.dispose();
    }//GEN-LAST:event_logoutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientEnterpriseAdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientEnterpriseAdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientEnterpriseAdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientEnterpriseAdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel patientAdminLeftJPanel;
    private javax.swing.JButton patientMangBtn;
    private javax.swing.JButton patientRegBtn;
    // End of variables declaration//GEN-END:variables
}
