/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.patientEnterPriseAdmin;

import com.entity.Network;
import com.entity.PatientEntity;
import com.repositories.PatientRepository;
import com.util.MailUtils;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.springframework.context.ApplicationContext;
import org.springframework.stereotype.Controller;

/**
 *
 * @author ajitpatil
 */
@Controller(value = "PatientManagerJPanel")
public class PatientManagerJPanel extends javax.swing.JPanel {

    private PatientRepository patientRepository;

    /**
     * Creates new form PatientManagerJPanel
     */
    public PatientManagerJPanel(
            PatientRepository patientRepository, ApplicationContext applicationContext) {
        this.patientRepository = applicationContext.getBean(PatientRepository.class);
        initComponents();
        loadAll();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        txtId = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtGender = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        patientIdLb = new javax.swing.JLabel();
        nameLb = new javax.swing.JLabel();
        ageLb = new javax.swing.JLabel();
        genderLb = new javax.swing.JLabel();
        addressLb = new javax.swing.JLabel();
        cityLb = new javax.swing.JLabel();
        txtState = new javax.swing.JTextField();
        stateLb = new javax.swing.JLabel();
        txtZipCode = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        zipcodelb = new javax.swing.JLabel();
        emailLb = new javax.swing.JLabel();
        concernLb = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtConcern = new javax.swing.JTextArea();
        viewPatient = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        mainImage1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1068, 719));
        setMinimumSize(new java.awt.Dimension(1068, 719));
        setPreferredSize(new java.awt.Dimension(1068, 719));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Patient Id", "Name", "Age", "Gender", "Address", "City", "State", "Zipcode", "Email", "Concern"
            }
        ));
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 730, 630));
        add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 96, -1));
        add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 96, -1));

        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 96, -1));
        add(txtGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 94, -1));
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 97, -1));
        add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 97, -1));

        patientIdLb.setText("Patient ID");
        add(patientIdLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 27, -1, -1));

        nameLb.setText("Name");
        add(nameLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 53, -1, -1));

        ageLb.setText("Age");
        add(ageLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 87, -1, -1));

        genderLb.setText("Gender");
        add(genderLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        addressLb.setText("Address");
        add(addressLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        cityLb.setText("City");
        add(cityLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));
        add(txtState, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 98, -1));

        stateLb.setText("State");
        add(stateLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));
        add(txtZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 98, -1));
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 96, -1));

        zipcodelb.setText("Zipcode");
        add(zipcodelb, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        emailLb.setText("Email");
        add(emailLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        concernLb.setText("Concern");
        add(concernLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        txtConcern.setColumns(20);
        txtConcern.setRows(5);
        jScrollPane2.setViewportView(txtConcern);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 117, 54));

        viewPatient.setText("View PatientRegistered");
        viewPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPatientActionPerformed(evt);
            }
        });
        add(viewPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 660, -1, -1));

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 110, -1));

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 660, 90, -1));

        mainImage1.setBackground(new java.awt.Color(41, 46, 64));
        mainImage1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        mainImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/Mentally Healthy Communities .jpg"))); // NOI18N
        mainImage1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 170, 170), 2));
        mainImage1.setMaximumSize(new java.awt.Dimension(728, 410));
        mainImage1.setMinimumSize(new java.awt.Dimension(728, 410));
        mainImage1.setOpaque(true);
        mainImage1.setPreferredSize(new java.awt.Dimension(728, 410));
        add(mainImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 700));
    }// </editor-fold>//GEN-END:initComponents

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed

//        appController.sendEmail();
        savePatient();
        loadAll();

        MailUtils.sendEmail(txtEmail.getText(), "Patient Registration Successfull!!", "Patient Registration Successfull");
        txtname.setText(" ");
        txtZipCode.setText(" ");
        txtId.setText(" ");
        txtAge.setText(" ");
        txtAddress.setText(" ");
        txtCity.setText(" ");
        txtState.setText(" ");
        txtConcern.setText(" ");
    }//GEN-LAST:event_updateBtnActionPerformed

    private void viewPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPatientActionPerformed
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();
        model.setRowCount(0);
        List<PatientEntity> findAll = patientRepository.findAll();
        for (PatientEntity entity : findAll) {

            Object[] data = {entity.getId(),
                entity.getName(), entity.getAge(),
                entity.getGender(),
                entity.getAddress(),
                entity.getCity(),
                entity.getState(),
                entity.getZipCode(),
                entity.getEmail(),
                entity.getConcern()};
            model.addRow(data);

        }
    }//GEN-LAST:event_viewPatientActionPerformed

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();
        if (model.getRowCount() != 0) {
            String id = model.getValueAt(tbl.getSelectedRow(), 0).toString();
            String name = model.getValueAt(tbl.getSelectedRow(), 1).toString();
            String age = model.getValueAt(tbl.getSelectedRow(), 2).toString();
            String gen = model.getValueAt(tbl.getSelectedRow(), 3).toString();
            String add = model.getValueAt(tbl.getSelectedRow(), 4).toString();
            String city = model.getValueAt(tbl.getSelectedRow(), 5).toString();
            String state = model.getValueAt(tbl.getSelectedRow(), 6).toString();
            String zip = model.getValueAt(tbl.getSelectedRow(), 7).toString();
            String email = model.getValueAt(tbl.getSelectedRow(), 8).toString();
            String concern = model.getValueAt(tbl.getSelectedRow(), 9).toString();

            txtId.setText(id);
            txtname.setText(name);
            txtAge.setText(age);
            txtGender.setText(gen);
            txtAddress.setText(add);
            txtCity.setText(city);
            txtState.setText(state);
            txtZipCode.setText(zip);
            txtEmail.setText(email);
            txtConcern.setText(concern);

        }
    }//GEN-LAST:event_tblMouseClicked

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        if (txtId.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please select one before delete");
        } else {
            patientRepository.deleteById(Integer.parseInt(txtId.getText()));
             JOptionPane.showMessageDialog(this, "Deleted");
        }

    }//GEN-LAST:event_deleteBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLb;
    private javax.swing.JLabel ageLb;
    private javax.swing.JLabel cityLb;
    private javax.swing.JLabel concernLb;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel emailLb;
    private javax.swing.JLabel genderLb;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel mainImage1;
    private javax.swing.JLabel nameLb;
    private javax.swing.JLabel patientIdLb;
    private javax.swing.JLabel stateLb;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextArea txtConcern;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtZipCode;
    private javax.swing.JTextField txtname;
    private javax.swing.JButton updateBtn;
    private javax.swing.JButton viewPatient;
    private javax.swing.JLabel zipcodelb;
    // End of variables declaration//GEN-END:variables

    private void savePatient() {
        try {
            PatientEntity patientEntity = new PatientEntity();

            String id = txtId.getText();
            String name = txtname.getText();
            String age = txtAge.getText();
            String gender = txtGender.getText();
            String address = txtAddress.getText();
            String city = txtCity.getText();
            String state = txtState.getText();
            String zip = txtZipCode.getText();
            String concern = txtConcern.getText();

            //set data in to the object class
            patientEntity.setId(Integer.parseInt(id));
            patientEntity.setName(name);
            patientEntity.setEmail(txtEmail.getText());
            patientEntity.setAge(Integer.parseInt(age));
            patientEntity.setGender(gender);
            patientEntity.setAddress(address);
            patientEntity.setCity(city);
            patientEntity.setState(state);
            patientEntity.setZipCode(Integer.parseInt(zip));
            patientEntity.setConcern(concern);
            patientEntity.setStatus("PENDING");

            //save patient from PatientRepository class
            patientRepository.save(patientEntity);
            JOptionPane.showMessageDialog(this, "Saved and sending the email..");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Failed");
        }
    }

    public int loadAll() {
        Integer lastId = patientRepository.getLastId();
        if (lastId != null) {
            lastId = lastId + 1;
        } else {
            lastId = 1;
        }
        txtId.setText(Integer.toString(lastId));
        return lastId;
    }
}
