/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.justiceEntAdmin;

import com.repositories.LoginDetailDetailRepository;
import com.view.CounselorPage;
import com.view.DoctorPage;
import com.view.LegalAdvisorPage;
import com.view.PatiendRegistration;
import com.view.PharmacyPage;
import com.view.PolicePage;
import com.view.Prisinorpage;
import com.view.PsychWardPage;
import com.view.RehabPage;
import com.view.SignUp;
import com.view.SystemAdminJFrame;
import org.springframework.context.ApplicationContext;
import org.springframework.stereotype.Controller;

/**
 *
 * @author ajitpatil
 */
@Controller(value = "JusticeEntAdminJFrame")
public class JusticeEntAdminJFrame extends javax.swing.JFrame {

    SystemAdminJFrame mainAdmin;
    PharmacyPage pharmacyPage;
    RehabPage rehabPage;
    LegalAdvisorPage legalAdvisorPage;
    PolicePage policePage;
    PsychWardPage psychWardPage;
    DoctorPage doctorPage;
    Prisinorpage prisinorpage;
    CounselorPage counselorPage;
    PatiendRegistration patiendRegistration;
    SignUp signUp;

    public JusticeEntAdminJFrame(SystemAdminJFrame mainAdmin,
            PharmacyPage pharmacyPage,
            RehabPage rehabPage,
            LegalAdvisorPage legalAdvisorPage,
            PolicePage policePage,
            PsychWardPage psychWardPage,
            DoctorPage doctorPage,
            Prisinorpage prisinorpage, CounselorPage counselorPage, PatiendRegistration patiendRegistration,
            SignUp signUp,
            ApplicationContext applicationContext) {
        this.mainAdmin = applicationContext.getBean(SystemAdminJFrame.class);
        this.pharmacyPage = applicationContext.getBean(PharmacyPage.class);
        this.rehabPage = applicationContext.getBean(RehabPage.class);
        this.legalAdvisorPage = applicationContext.getBean(LegalAdvisorPage.class);
        this.policePage = applicationContext.getBean(PolicePage.class);
        this.psychWardPage = applicationContext.getBean(PsychWardPage.class);
        this.doctorPage = applicationContext.getBean(DoctorPage.class);
        this.prisinorpage = applicationContext.getBean(Prisinorpage.class);
        this.counselorPage = applicationContext.getBean(CounselorPage.class);
        this.patiendRegistration = applicationContext.getBean(PatiendRegistration.class);
        this.signUp = applicationContext.getBean(SignUp.class);

        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jailAdminBtn = new javax.swing.JButton();
        closeBtn = new javax.swing.JButton();
        legalAdminBtn = new javax.swing.JButton();
        policeBtn = new javax.swing.JButton();
        mainImage1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jailAdminBtn.setText("JailAdminView");
        jailAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jailAdminBtnActionPerformed(evt);
            }
        });
        getContentPane().add(jailAdminBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 98, 133, 184));

        closeBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        closeBtn.setText("CLOSE");
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, -1, -1));

        legalAdminBtn.setText("LegalView");
        legalAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                legalAdminBtnActionPerformed(evt);
            }
        });
        getContentPane().add(legalAdminBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 98, 126, 184));

        policeBtn.setText("PoliceView");
        policeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                policeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(policeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 98, 130, 184));

        mainImage1.setBackground(new java.awt.Color(41, 46, 64));
        mainImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/Mentally Healthy Communities .jpg"))); // NOI18N
        mainImage1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 170, 170), 2));
        mainImage1.setMaximumSize(new java.awt.Dimension(728, 410));
        mainImage1.setMinimumSize(new java.awt.Dimension(728, 410));
        mainImage1.setOpaque(true);
        mainImage1.setPreferredSize(new java.awt.Dimension(728, 410));
        getContentPane().add(mainImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jailAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jailAdminBtnActionPerformed
        prisinorpage.setVisible(true);
    }//GEN-LAST:event_jailAdminBtnActionPerformed

    private void legalAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_legalAdminBtnActionPerformed
        legalAdvisorPage.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_legalAdminBtnActionPerformed

    private void policeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_policeBtnActionPerformed
        policePage.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_policeBtnActionPerformed

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JusticeEntAdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JusticeEntAdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JusticeEntAdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JusticeEntAdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeBtn;
    private javax.swing.JButton jailAdminBtn;
    private javax.swing.JButton legalAdminBtn;
    private javax.swing.JLabel mainImage1;
    private javax.swing.JButton policeBtn;
    // End of variables declaration//GEN-END:variables
}
