/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view;

import org.springframework.context.ApplicationContext;
import org.springframework.stereotype.Controller;

 
@Controller(value = "CounselorPage")
public class CounselorPage extends javax.swing.JFrame {

    CouncelorPrisonPatiendPanel prisonPatientPanel;
    ViewPatientPanel patientPanel;

    /**
     * Creates new form CounselorPage
     */
    public CounselorPage(CouncelorPrisonPatiendPanel prisonPatientPanel, ViewPatientPanel patientPanel,
            ApplicationContext applicationContext) {
        this.prisonPatientPanel = applicationContext.getBean(CouncelorPrisonPatiendPanel.class);
        this.patientPanel = applicationContext.getBean(ViewPatientPanel.class);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        viewPatientBtn = new javax.swing.JButton();
        viewPrisonerPatientBtn = new javax.swing.JButton();
        closeBtn = new javax.swing.JButton();
        mainImage1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1048, Short.MAX_VALUE)
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );

        getContentPane().add(panelMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 1050, 700));

        viewPatientBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        viewPatientBtn.setText("VIEW PATIENT");
        viewPatientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPatientBtnActionPerformed(evt);
            }
        });
        getContentPane().add(viewPatientBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 200, 40));

        viewPrisonerPatientBtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        viewPrisonerPatientBtn.setText("VIEW PRISINOR PATIENT");
        viewPrisonerPatientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPrisonerPatientBtnActionPerformed(evt);
            }
        });
        getContentPane().add(viewPrisonerPatientBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 200, 40));

        closeBtn.setBackground(new java.awt.Color(255, 0, 0));
        closeBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        closeBtn.setText("CLOSE");
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 200, 40));

        mainImage1.setBackground(new java.awt.Color(41, 46, 64));
        mainImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/Mentally Healthy Communities .jpg"))); // NOI18N
        mainImage1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 170, 170), 2));
        mainImage1.setMaximumSize(new java.awt.Dimension(728, 410));
        mainImage1.setMinimumSize(new java.awt.Dimension(728, 410));
        mainImage1.setOpaque(true);
        mainImage1.setPreferredSize(new java.awt.Dimension(728, 410));
        getContentPane().add(mainImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewPatientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPatientBtnActionPerformed
        panelMain.removeAll();
        patientPanel.setSize(panelMain.getSize());
        panelMain.add(patientPanel);
        panelMain.repaint();
        panelMain.revalidate();        // TODO add your handling code here:
    }//GEN-LAST:event_viewPatientBtnActionPerformed

    private void viewPrisonerPatientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPrisonerPatientBtnActionPerformed

        panelMain.removeAll();
        prisonPatientPanel.setSize(panelMain.getSize());
        panelMain.add(prisonPatientPanel);
        panelMain.repaint();
        panelMain.revalidate();      
    }//GEN-LAST:event_viewPrisonerPatientBtnActionPerformed

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_closeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CounselorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CounselorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CounselorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CounselorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeBtn;
    private javax.swing.JLabel mainImage1;
    private javax.swing.JPanel panelMain;
    private javax.swing.JButton viewPatientBtn;
    private javax.swing.JButton viewPrisonerPatientBtn;
    // End of variables declaration//GEN-END:variables
}
