/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view;

import com.entity.PrisonPatientEntity;
import com.entity.PrisonPatientVitalEntity;
import com.repositories.PatientRepositoryPrison;
import com.repositories.PrisonPatientVitalRepository;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.springframework.context.ApplicationContext;
import org.springframework.stereotype.Controller;

@Controller(value = "CouncelorPrisonPatiendPanel")
public class CouncelorPrisonPatiendPanel extends javax.swing.JPanel {

    PatientRepositoryPrison patientRepository;
    PrisonPatientVitalRepository patientVitalRepository;
    private Integer patientVitalId;

    /**
     * Creates new form ViewPatientPanel
     */
    public CouncelorPrisonPatiendPanel(PrisonPatientVitalRepository patientVitalRepository,
            PatientRepositoryPrison patientRepository,
            ApplicationContext applicationContext) {
        this.patientVitalRepository = applicationContext.getBean(PrisonPatientVitalRepository.class);
        this.patientRepository = applicationContext.getBean(PatientRepositoryPrison.class);
        initComponents();
        loadPatients();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        tbl1 = new javax.swing.JTable();
        gad7Lb = new javax.swing.JLabel();
        patientIdLb = new javax.swing.JLabel();
        patientNameLb = new javax.swing.JLabel();
        gad7ScoreCombo = new javax.swing.JComboBox<>();
        bpLb = new javax.swing.JLabel();
        weightLb = new javax.swing.JLabel();
        phq9scoreLb = new javax.swing.JLabel();
        sendtoDocBtn = new javax.swing.JButton();
        saveVitalbtn = new javax.swing.JButton();
        phq9ScoreCombo = new javax.swing.JComboBox<>();
        txtBp = new javax.swing.JTextField();
        txtWeight = new javax.swing.JTextField();
        txtPatientId = new javax.swing.JTextField();
        txtPatientName = new javax.swing.JTextField();
        reloadBtn = new javax.swing.JButton();
        mainImage1 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setMaximumSize(new java.awt.Dimension(1050, 700));
        setMinimumSize(new java.awt.Dimension(1050, 700));
        setPreferredSize(new java.awt.Dimension(1050, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PATIENT ID", "PATIENT NAME", "PATIENT STATUS"
            }
        ));
        tbl1.setRowHeight(30);
        tbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl1MouseClicked(evt);
            }
        });
        jScrollPane.setViewportView(tbl1);

        add(jScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 990, 310));

        gad7Lb.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        gad7Lb.setText("GAD-7 SCORE");
        add(gad7Lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 570, 120, 35));

        patientIdLb.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        patientIdLb.setText("PATIENT ID");
        add(patientIdLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 90, 35));

        patientNameLb.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        patientNameLb.setText("PATIENT NAME");
        add(patientNameLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 110, 35));

        gad7ScoreCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21" }));
        add(gad7ScoreCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 570, 280, -1));

        bpLb.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        bpLb.setText("BLOODPRESSURE");
        add(bpLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 130, 35));

        weightLb.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        weightLb.setText("WEIGHT");
        add(weightLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, 60, 35));

        phq9scoreLb.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        phq9scoreLb.setText("PHQ-9 SCORE");
        add(phq9scoreLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 530, 100, 30));

        sendtoDocBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        sendtoDocBtn.setText("SEND DETAILS TO DOCTOR");
        sendtoDocBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendtoDocBtnActionPerformed(evt);
            }
        });
        add(sendtoDocBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 620, 250, 35));

        saveVitalbtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        saveVitalbtn.setText("SAVE PATIENT VITAL");
        saveVitalbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveVitalbtnActionPerformed(evt);
            }
        });
        add(saveVitalbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 620, 260, 35));

        phq9ScoreCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27" }));
        add(phq9ScoreCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 530, 280, -1));

        txtBp.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtBp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBpKeyTyped(evt);
            }
        });
        add(txtBp, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, 280, 35));

        txtWeight.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtWeight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtWeightKeyTyped(evt);
            }
        });
        add(txtWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 480, 280, 35));

        txtPatientId.setEditable(false);
        txtPatientId.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        add(txtPatientId, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 280, 35));

        txtPatientName.setEditable(false);
        txtPatientName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        add(txtPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 280, 35));

        reloadBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        reloadBtn.setText("Reload");
        reloadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reloadBtnActionPerformed(evt);
            }
        });
        add(reloadBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(903, 340, 110, 40));

        mainImage1.setBackground(new java.awt.Color(41, 46, 64));
        mainImage1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        mainImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/Mentally Healthy Communities .jpg"))); // NOI18N
        mainImage1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 170, 170), 2));
        mainImage1.setMaximumSize(new java.awt.Dimension(728, 410));
        mainImage1.setMinimumSize(new java.awt.Dimension(728, 410));
        mainImage1.setOpaque(true);
        mainImage1.setPreferredSize(new java.awt.Dimension(728, 410));
        add(mainImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 700));
    }// </editor-fold>//GEN-END:initComponents

    private void tbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl1MouseClicked
        DefaultTableModel model = (DefaultTableModel) tbl1.getModel();
        if (model.getRowCount() != 0) {
            String id = model.getValueAt(tbl1.getSelectedRow(), 0).toString();
            String name = model.getValueAt(tbl1.getSelectedRow(), 1).toString();
            txtPatientId.setText(id);
            txtPatientName.setText(name);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl1MouseClicked

    private void reloadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reloadBtnActionPerformed
        loadPatients();        // TODO add your handling code here:
    }//GEN-LAST:event_reloadBtnActionPerformed

    private void sendtoDocBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendtoDocBtnActionPerformed
        PrisonPatientEntity finddetailById = patientRepository.finddetailById(Integer.parseInt(txtPatientId.getText()));
        finddetailById.setId(finddetailById.getId());
        finddetailById.setStatus("Sent to Doctor");
        patientRepository.save(finddetailById);
        JOptionPane.showMessageDialog(this, "Sent the Vitals to Doctor"); 
        
    }//GEN-LAST:event_sendtoDocBtnActionPerformed

    private void saveVitalbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveVitalbtnActionPerformed
        try {

            if (txtWeight.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Weight cannot be empty");
            } else {
                PrisonPatientVitalEntity entity = new PrisonPatientVitalEntity();
                if (patientVitalId == null) {
                    entity.setId(null);
                } else {
                    entity.setId(patientVitalId);
                }
                entity.setBp(txtBp.getText());
               // entity.setGad(txtGad.getText());
                entity.setGad(gad7ScoreCombo.getSelectedItem().toString());
                entity.setWeight(txtWeight.getText());
                //entity.setPhq(txtPhq.getText());
                entity.setPhq(phq9ScoreCombo.getSelectedItem().toString());
                entity.setPatientId(Integer.parseInt(txtPatientId.getText()));
                PrisonPatientVitalEntity save = patientVitalRepository.save(entity);
                patientVitalId = save.getId();
                JOptionPane.showMessageDialog(this, "Saved the Patient Vitals");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Failed");
        }
    }//GEN-LAST:event_saveVitalbtnActionPerformed

    private void txtBpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBpKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
				if (Character.isDigit(c) || Character.isISOControl(c)) {
					txtBp.setEditable(true);
				}
				else {
					JOptionPane.showMessageDialog(this, "Blood Pressure must be Integer value");
					txtBp.setEditable(false);
				}
        
    }//GEN-LAST:event_txtBpKeyTyped

    private void txtWeightKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWeightKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
				if (Character.isDigit(c) || Character.isISOControl(c)) {
					txtWeight.setEditable(true);
				}
				else {
					JOptionPane.showMessageDialog(this, "Weight must be Integer value");
					txtWeight.setEditable(false);
				} 
        
    }//GEN-LAST:event_txtWeightKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bpLb;
    private javax.swing.JLabel gad7Lb;
    private javax.swing.JComboBox<String> gad7ScoreCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel mainImage1;
    private javax.swing.JLabel patientIdLb;
    private javax.swing.JLabel patientNameLb;
    private javax.swing.JComboBox<String> phq9ScoreCombo;
    private javax.swing.JLabel phq9scoreLb;
    private javax.swing.JButton reloadBtn;
    private javax.swing.JButton saveVitalbtn;
    private javax.swing.JButton sendtoDocBtn;
    private javax.swing.JTable tbl1;
    private javax.swing.JTextField txtBp;
    private javax.swing.JTextField txtPatientId;
    private javax.swing.JTextField txtPatientName;
    private javax.swing.JTextField txtWeight;
    private javax.swing.JLabel weightLb;
    // End of variables declaration//GEN-END:variables

    private void loadPatients() {
        DefaultTableModel model = (DefaultTableModel) tbl1.getModel();
        model.setRowCount(0);
        List<PrisonPatientEntity> findAll = patientRepository.findAll();
        for (PrisonPatientEntity entity : findAll) {
            if (entity.getStatus().equals("Sent to Councelor")) {
                Object[] data = {entity.getId(),
                    entity.getName(), entity.getStatus()};

                model.addRow(data);
            }

        }
    }
}
