/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view;

import com.entity.PatientDiagnoseEntity;
import com.entity.PatientEntity;
import com.entity.PatientVitalEntity;
import com.repositories.PatientDiagnoseRepository;
import com.repositories.PatientRepository;
import com.repositories.PatientVitalRepository;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.springframework.context.ApplicationContext;
import org.springframework.stereotype.Controller;

@Controller(value = "DoctorDiagnoesePatientPanel")
public class DoctorDiagnoesePatientPanel extends javax.swing.JPanel {

    PatientDiagnoseRepository diagnoseRepository;
    PatientVitalRepository patientVitalRepository;
    PatientRepository patientRepository;

    /**
     * Creates new form DoctorDiagnoesePatientPanel
     */
    public DoctorDiagnoesePatientPanel(PatientDiagnoseRepository diagnoseRepository,
            PatientRepository patientRepository,
            PatientVitalRepository patientVitalRepository,
            ApplicationContext applicationContext) {
        this.diagnoseRepository = applicationContext.getBean(PatientDiagnoseRepository.class);
        this.patientVitalRepository = applicationContext.getBean(PatientVitalRepository.class);
        this.patientRepository = applicationContext.getBean(PatientRepository.class);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPatient = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        doctorDiagonsisLb = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        prescriptionLb = new javax.swing.JLabel();
        patientIDLb = new javax.swing.JLabel();
        patientNameLb = new javax.swing.JLabel();
        doctorNameLb = new javax.swing.JLabel();
        issueTypeLb = new javax.swing.JLabel();
        caseSeverityLb = new javax.swing.JLabel();
        rehabreqLb = new javax.swing.JLabel();
        doctorCommentsLb = new javax.swing.JLabel();
        txtPrescription = new javax.swing.JTextField();
        txtPatientId = new javax.swing.JTextField();
        txtPatientName = new javax.swing.JTextField();
        issueCombo = new javax.swing.JComboBox<>();
        txtDranema = new javax.swing.JTextField();
        caseSeverCombo = new javax.swing.JComboBox<>();
        txtComments = new javax.swing.JTextField();
        radioNo = new javax.swing.JRadioButton();
        radioYes = new javax.swing.JRadioButton();
        pharmacyBtn = new javax.swing.JButton();
        rehabBtn = new javax.swing.JButton();
        mainImage1 = new javax.swing.JLabel();
        mainImage2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1050, 700));
        setMinimumSize(new java.awt.Dimension(1050, 700));
        setPreferredSize(new java.awt.Dimension(1050, 700));

        tblPatient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PATIENT ID", "NAME", "AGE", "BP", "WEIGHT", "PHQ-9 SCORE", "GAD-7 SCORE", "STATUS"
            }
        ));
        tblPatient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPatientMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPatient);

        jButton1.setBackground(new java.awt.Color(255, 102, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("GET MY PATIENTS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        doctorDiagonsisLb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        doctorDiagonsisLb.setText("DOCTOR DIAGONSIS");

        txtName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("ENTER YOUR NAME");

        prescriptionLb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        prescriptionLb.setText("PRESCRIPTION");

        patientIDLb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        patientIDLb.setText("PATIENT ID");

        patientNameLb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        patientNameLb.setText("PATIENT NAME");

        doctorNameLb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        doctorNameLb.setText("DOCTOR NAME");

        issueTypeLb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        issueTypeLb.setText("ISSUE TYPE");

        caseSeverityLb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        caseSeverityLb.setText("CASE SERVERITY");

        rehabreqLb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rehabreqLb.setText("REHAB REQUIRED");

        doctorCommentsLb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        doctorCommentsLb.setText("DOCTOR COMMENTS");

        txtPrescription.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPrescription.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrescriptionKeyTyped(evt);
            }
        });

        txtPatientId.setEditable(false);
        txtPatientId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtPatientName.setEditable(false);
        txtPatientName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        issueCombo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        issueCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PTSD", "BIPOLAR DISORDER", "SCHIZOPHRENIA", "AUTISM", " " }));

        txtDranema.setEditable(false);
        txtDranema.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        caseSeverCombo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        caseSeverCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LOW", "MEDIUM", "HIGH", " " }));

        txtComments.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtComments.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCommentsKeyTyped(evt);
            }
        });

        buttonGroup1.add(radioNo);
        radioNo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        radioNo.setText("NO");

        buttonGroup1.add(radioYes);
        radioYes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        radioYes.setText("YES");

        pharmacyBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pharmacyBtn.setText("SEND TO PHARMACY");
        pharmacyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pharmacyBtnActionPerformed(evt);
            }
        });

        rehabBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rehabBtn.setText("SEND TO REHAB");
        rehabBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rehabBtnActionPerformed(evt);
            }
        });

        mainImage1.setBackground(new java.awt.Color(41, 46, 64));
        mainImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/Mentally Healthy Communities .jpg"))); // NOI18N
        mainImage1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 170, 170), 2));
        mainImage1.setMaximumSize(new java.awt.Dimension(728, 410));
        mainImage1.setMinimumSize(new java.awt.Dimension(728, 410));
        mainImage1.setOpaque(true);
        mainImage1.setPreferredSize(new java.awt.Dimension(728, 410));

        mainImage2.setBackground(new java.awt.Color(41, 46, 64));
        mainImage2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        mainImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/Mentally Healthy Communities .jpg"))); // NOI18N
        mainImage2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 170, 170), 2));
        mainImage2.setMaximumSize(new java.awt.Dimension(728, 410));
        mainImage2.setMinimumSize(new java.awt.Dimension(728, 410));
        mainImage2.setOpaque(true);
        mainImage2.setPreferredSize(new java.awt.Dimension(728, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(430, 430, 430)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(patientIDLb, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(patientNameLb, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(doctorNameLb, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(txtDranema, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(issueTypeLb, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(issueCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(caseSeverityLb, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(caseSeverCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(rehabreqLb, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(radioNo))
            .addGroup(layout.createSequentialGroup()
                .addGap(330, 330, 330)
                .addComponent(doctorCommentsLb, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(txtComments, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(prescriptionLb, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(250, 250, 250)
                .addComponent(pharmacyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(500, 500, 500)
                .addComponent(radioYes))
            .addGroup(layout.createSequentialGroup()
                .addGap(740, 740, 740)
                .addComponent(rehabBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(doctorDiagonsisLb))
            .addComponent(mainImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(500, 500, 500)
                .addComponent(txtPrescription, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(500, 500, 500)
                .addComponent(txtPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(mainImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 1050, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(280, 280, 280)
                .addComponent(patientIDLb, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(patientNameLb, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doctorNameLb, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDranema, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(issueTypeLb, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(issueCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(caseSeverityLb, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(caseSeverCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rehabreqLb, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doctorCommentsLb, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtComments, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prescriptionLb, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pharmacyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(520, 520, 520)
                .addComponent(radioYes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(550, 550, 550)
                .addComponent(rehabBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(doctorDiagonsisLb))
            .addComponent(mainImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(600, 600, 600)
                .addComponent(txtPrescription, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(txtPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(mainImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (txtName.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter your name to get patients");
        } else {
            loadPatients();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblPatientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPatientMouseClicked
        DefaultTableModel model = (DefaultTableModel) tblPatient.getModel();
        if (model.getRowCount() != 0) {
            String id = model.getValueAt(tblPatient.getSelectedRow(), 0).toString();
            String name = model.getValueAt(tblPatient.getSelectedRow(), 1).toString();
            String drName = txtName.getText();
            txtPatientId.setText(id);
            txtPatientName.setText(name);
            PatientEntity finddetailById = patientRepository.finddetailById(Integer.parseInt(txtPatientId.getText()));

            txtDranema.setText(finddetailById.getDoctorId());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_tblPatientMouseClicked

    private void rehabBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rehabBtnActionPerformed
        PatientEntity finddetailById = patientRepository.finddetailById(Integer.parseInt(txtPatientId.getText()));
        finddetailById.setStatus("Sent to Rehab");

        patientRepository.save(finddetailById);
        saveDiagnose();
        JOptionPane.showMessageDialog(this, "Patient Sent to Rehab");
        txtPatientId.setText(" ");
        txtPatientName.setText(" ");
        txtDranema.setText(" ");
        txtComments.setText(" ");
        txtPrescription.setText(" ");
    }//GEN-LAST:event_rehabBtnActionPerformed

    private void pharmacyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pharmacyBtnActionPerformed
        PatientEntity finddetailById = patientRepository.finddetailById(Integer.parseInt(txtPatientId.getText()));
        finddetailById.setStatus("Sent to Pharmacy");

        patientRepository.save(finddetailById);
        saveDiagnose();
        JOptionPane.showMessageDialog(this, "Patient prescription details sent to Pharmacy");
        txtPatientId.setText(" ");
        txtPatientName.setText(" ");
        txtDranema.setText(" ");
        txtComments.setText(" ");
        txtPrescription.setText(" ");
                
    }//GEN-LAST:event_pharmacyBtnActionPerformed

    private void txtCommentsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCommentsKeyTyped
        // TODO add your handling code here:
       char c = evt.getKeyChar();
        if (Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)) {
            //allow only letter,space and Iso control char

            txtComments.setEditable(true);
        } else {
            JOptionPane.showMessageDialog(this, "Comments must be a String value");
            txtComments.setEditable(false);

        }  
        
    }//GEN-LAST:event_txtCommentsKeyTyped

    private void txtPrescriptionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrescriptionKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)) {
            //allow only letter,space and Iso control char

            txtPrescription.setEditable(true);
        } else {
            JOptionPane.showMessageDialog(this, "Prescription must be a String value");
            txtPrescription.setEditable(false);

        } 
        
    }//GEN-LAST:event_txtPrescriptionKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> caseSeverCombo;
    private javax.swing.JLabel caseSeverityLb;
    private javax.swing.JLabel doctorCommentsLb;
    private javax.swing.JLabel doctorDiagonsisLb;
    private javax.swing.JLabel doctorNameLb;
    private javax.swing.JComboBox<String> issueCombo;
    private javax.swing.JLabel issueTypeLb;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel mainImage1;
    private javax.swing.JLabel mainImage2;
    private javax.swing.JLabel patientIDLb;
    private javax.swing.JLabel patientNameLb;
    private javax.swing.JButton pharmacyBtn;
    private javax.swing.JLabel prescriptionLb;
    private javax.swing.JRadioButton radioNo;
    private javax.swing.JRadioButton radioYes;
    private javax.swing.JButton rehabBtn;
    private javax.swing.JLabel rehabreqLb;
    private javax.swing.JTable tblPatient;
    private javax.swing.JTextField txtComments;
    private javax.swing.JTextField txtDranema;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPatientId;
    private javax.swing.JTextField txtPatientName;
    private javax.swing.JTextField txtPrescription;
    // End of variables declaration//GEN-END:variables

    private void loadPatients() {
        DefaultTableModel model = (DefaultTableModel) tblPatient.getModel();
        model.setRowCount(0);
        List<PatientEntity> findAll = patientRepository.findAll();
        for (PatientEntity entity : findAll) {
            if (entity.getStatus().equals("Doctor Assigned") && entity.getDoctorId().equals(txtName.getText())) {
                //PatientVitalEntity finddetailById = patientVitalRepository.finddetailById(Integer.toString(entity.getId()));
                PatientVitalEntity finddetailById = patientVitalRepository.finddetailById(entity.getId());
                if (null != finddetailById) {
                    Object[] data = {entity.getId(),
                        entity.getName(), entity.getAge(),
                        finddetailById.getBp(),
                        finddetailById.getWeight(),
                        finddetailById.getPhq(),
                        finddetailById.getGad(),
                        entity.getStatus()};

                    model.addRow(data);
                }
            }

        }
    }

    private void saveDiagnose() {
        PatientDiagnoseEntity diagnoseEntity = new PatientDiagnoseEntity();
        diagnoseEntity.setId(null);
       // diagnoseEntity.setCaseSer(txtCase.getText());
          diagnoseEntity.setCaseSer(caseSeverCombo.getSelectedItem().toString());
        diagnoseEntity.setComments(txtComments.getText());
        diagnoseEntity.setDrname(txtDranema.getText());
        //String role = issueCombo.getSelectedItem().toString();
        //diagnoseEntity.setIssueType(txtIssueType.getText());
        diagnoseEntity.setIssueType(issueCombo.getSelectedItem().toString());
        diagnoseEntity.setName(txtPatientName.getText());
        diagnoseEntity.setPatientId(Integer.parseInt(txtPatientId.getText()));
        diagnoseEntity.setPrescription(txtPrescription.getText());
        if (radioNo.isSelected()) {
            diagnoseEntity.setSetRehab("NO");
        }
        if (radioYes.isSelected()) {
            diagnoseEntity.setSetRehab("YES");
        }
        diagnoseRepository.save(diagnoseEntity);

    }

}
