/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view;

import org.springframework.context.ApplicationContext;
import org.springframework.stereotype.Controller;

 
@Controller(value = "DoctorPage")
public class DoctorPage extends javax.swing.JFrame {

    DoctorRehabPanel doctorRehabPanel;
    DoctorDiagnoesePatientPanel diagnoesePatientPanel;
    DoctorDiagnoesePrisonPatientPanel diagnoesePrisonPatientPanel;
    DoctorPatientPanel doctorPatientPanel;

    /**
     * Creates new form CounselorPage
     */
    public DoctorPage(DoctorRehabPanel doctorRehabPanel, DoctorDiagnoesePatientPanel diagnoesePatientPanel,
            DoctorDiagnoesePrisonPatientPanel diagnoesePrisonPatientPanel,
            DoctorPatientPanel doctorPatientPanel,
            ApplicationContext applicationContext) {
        this.doctorRehabPanel = applicationContext.getBean(DoctorRehabPanel.class);
        this.diagnoesePatientPanel = applicationContext.getBean(DoctorDiagnoesePatientPanel.class);
        this.diagnoesePrisonPatientPanel = applicationContext.getBean(DoctorDiagnoesePrisonPatientPanel.class);
        this.doctorPatientPanel = applicationContext.getBean(DoctorPatientPanel.class);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        viewPatientBtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        diagnosePrisonerPatBtn = new javax.swing.JButton();
        diagonsePatientsBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        mainImage1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1048, Short.MAX_VALUE)
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );

        getContentPane().add(panelMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 1050, 700));

        viewPatientBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        viewPatientBtn.setText("VIEW PATIENT");
        viewPatientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPatientBtnActionPerformed(evt);
            }
        });
        getContentPane().add(viewPatientBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 200, 40));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Rehab View");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 200, 40));

        diagnosePrisonerPatBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        diagnosePrisonerPatBtn.setText("Diagnose Prisinors");
        diagnosePrisonerPatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diagnosePrisonerPatBtnActionPerformed(evt);
            }
        });
        getContentPane().add(diagnosePrisonerPatBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 200, 40));

        diagonsePatientsBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        diagonsePatientsBtn.setText("Diagnose Patients");
        diagonsePatientsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diagonsePatientsBtnActionPerformed(evt);
            }
        });
        getContentPane().add(diagonsePatientsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 200, 40));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("CLOSE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 200, 40));

        mainImage1.setBackground(new java.awt.Color(41, 46, 64));
        mainImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/Mentally Healthy Communities .jpg"))); // NOI18N
        mainImage1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 170, 170), 2));
        mainImage1.setMaximumSize(new java.awt.Dimension(728, 410));
        mainImage1.setMinimumSize(new java.awt.Dimension(728, 410));
        mainImage1.setOpaque(true);
        mainImage1.setPreferredSize(new java.awt.Dimension(728, 410));
        getContentPane().add(mainImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewPatientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPatientBtnActionPerformed
        panelMain.removeAll();
        doctorPatientPanel.setSize(panelMain.getSize());
        panelMain.add(doctorPatientPanel);
        panelMain.repaint();
        panelMain.revalidate();
    }//GEN-LAST:event_viewPatientBtnActionPerformed

    private void diagnosePrisonerPatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diagnosePrisonerPatBtnActionPerformed
        panelMain.removeAll();
        diagnoesePrisonPatientPanel.setSize(panelMain.getSize());
        panelMain.add(diagnoesePrisonPatientPanel);
        panelMain.repaint();
        panelMain.revalidate();// TODO add your handling code here:
    }//GEN-LAST:event_diagnosePrisonerPatBtnActionPerformed

    private void diagonsePatientsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diagonsePatientsBtnActionPerformed

        panelMain.removeAll();
        diagnoesePatientPanel.setSize(panelMain.getSize());
        panelMain.add(diagnoesePatientPanel);
        panelMain.repaint();
        panelMain.revalidate();// TODO add your handling code here:
    }//GEN-LAST:event_diagonsePatientsBtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        panelMain.removeAll();
        doctorRehabPanel.setSize(panelMain.getSize());
        panelMain.add(doctorRehabPanel);
        panelMain.repaint();
        panelMain.revalidate();// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton diagnosePrisonerPatBtn;
    private javax.swing.JButton diagonsePatientsBtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel mainImage1;
    private javax.swing.JPanel panelMain;
    private javax.swing.JButton viewPatientBtn;
    // End of variables declaration//GEN-END:variables

}
