/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.view;

import com.entity.LoginDetails;
import com.util.EmailValidator;
import com.entity.Network;
import com.repositories.LoginDetailDetailRepository;
import com.util.EmailValidator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.springframework.context.ApplicationContext;
import org.springframework.stereotype.Controller;

/**
 *
 * @author ajitpatil
 */
@Controller(value = "ManageUsersJPanel")
public class ManageUsersJPanel extends javax.swing.JPanel {
private JPanel ManageUsersJPanel;
    private LoginDetailDetailRepository loginDetailDetailRepository;

    /**
     * Creates new form ManageUsersJPanel
     */
    public ManageUsersJPanel(LoginDetailDetailRepository loginDetailDetailRepository, ApplicationContext applicationContext) {
        initComponents();
        this.loginDetailDetailRepository = applicationContext.getBean(LoginDetailDetailRepository.class);
        loadUsers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUserName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        cmbRolesName = new javax.swing.JComboBox<>();
        txtEmail = new javax.swing.JTextField();
        txtContact = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPatient = new javax.swing.JTable();
        lblId = new javax.swing.JLabel();
        passwordLb = new javax.swing.JLabel();
        roleNameLb = new javax.swing.JLabel();
        emailLb = new javax.swing.JLabel();
        conatctLb = new javax.swing.JLabel();
        saveLb = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        UserNameLb1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        mainImage1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUserName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUserNameKeyTyped(evt);
            }
        });
        add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 290, 35));

        txtPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 290, 35));

        cmbRolesName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbRolesName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PATIENT", "COUNSELOR", "JAILADMIN", "DOCTOR", "PHARMACY", "REHAB", "LEGAL ADVISOR", "POLICE", "PSYCH WARD", "PATIENTENTADMIN", "HOSPITALENTADMIN", "JUSTICEENTADMIN", "PHYSCHENTADMIN", " " }));
        cmbRolesName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRolesNameActionPerformed(evt);
            }
        });
        add(cmbRolesName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 290, 35));

        txtEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 290, 35));

        txtContact.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtContact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContactKeyTyped(evt);
            }
        });
        add(txtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 290, 35));

        tblPatient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "UserName", "Password", "Rolename", "EmailId", "Conatct"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblPatient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPatientMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPatient);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 23, 570, 480));
        add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 74, 40));

        passwordLb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        passwordLb.setText("Password");
        add(passwordLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 150, 35));

        roleNameLb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        roleNameLb.setText("RoleName");
        add(roleNameLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 150, 35));

        emailLb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        emailLb.setText("EmailID");
        add(emailLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 150, 35));

        conatctLb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        conatctLb.setText("Contact");
        add(conatctLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 150, 35));

        saveLb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        saveLb.setText("Save");
        saveLb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveLbActionPerformed(evt);
            }
        });
        add(saveLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 290, 35));

        updateBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 290, 35));

        deleteBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 290, 35));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("reload");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(716, 530, 150, 35));

        UserNameLb1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UserNameLb1.setText("UserName");
        add(UserNameLb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 150, 35));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 521, -1, -1));

        mainImage1.setBackground(new java.awt.Color(41, 46, 64));
        mainImage1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        mainImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/Mentally Healthy Communities .jpg"))); // NOI18N
        mainImage1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 170, 170), 2));
        mainImage1.setMaximumSize(new java.awt.Dimension(728, 410));
        mainImage1.setMinimumSize(new java.awt.Dimension(728, 410));
        mainImage1.setOpaque(true);
        mainImage1.setPreferredSize(new java.awt.Dimension(728, 410));
        add(mainImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 700));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        loadUsers();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblPatientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPatientMouseClicked
        DefaultTableModel model = (DefaultTableModel) tblPatient.getModel();
        if (model.getRowCount() != 0) {
            String city = model.getValueAt(tblPatient.getSelectedRow(), 0).toString();
            LoginDetails finddetailByCity = loginDetailDetailRepository.getDetailById(city);
            if (null != finddetailByCity) {
                lblId.setText(Long.toString(finddetailByCity.getId()));
                txtUserName.setText(finddetailByCity.getUsername());
                txtPassword.setText(finddetailByCity.getUserPassword());
                txtEmail.setText(finddetailByCity.getEmail());
                txtContact.setText(finddetailByCity.getContactNo());
                cmbRolesName.setSelectedItem(finddetailByCity.getRoleName());
            }
        }     // TODO add your handling code here:
    }//GEN-LAST:event_tblPatientMouseClicked

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        if (!lblId.getText().equals("")) {
            loginDetailDetailRepository.deleteById(Integer.parseInt(lblId.getText()));
        } else {
            JOptionPane.showMessageDialog(this, "Please search or select record to delete");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void saveLbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveLbActionPerformed
         EmailValidator emailValidator = new EmailValidator();
        if (!emailValidator.validate(txtEmail.getText().trim())) {
            JOptionPane.showMessageDialog(this, "Invalid Email !!");

        } else{
        LoginDetails network = new LoginDetails();
        network.setId(null);
        network.setUsername(txtUserName.getText());
        network.setUserPassword(txtPassword.getText());
        network.setRoleName(cmbRolesName.getSelectedItem().toString());
        network.setEmail(txtEmail.getText());
        network.setContactNo(txtContact.getText());
        loginDetailDetailRepository.save(network);
        JOptionPane.showMessageDialog(this, "USER Registered");
        }
    }//GEN-LAST:event_saveLbActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        LoginDetails network = new LoginDetails();
        network.setId(Integer.parseInt(lblId.getText()));
        network.setUsername(txtUserName.getText());
        network.setUserPassword(txtPassword.getText());
        network.setRoleName(cmbRolesName.getSelectedItem().toString());
        network.setEmail(txtEmail.getText());
        network.setContactNo(txtContact.getText());
        loginDetailDetailRepository.save(network);
        JOptionPane.showMessageDialog(this, "Saved");        // TODO add your handling code here:
    }//GEN-LAST:event_updateBtnActionPerformed

    private void txtUserNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserNameKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if (Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)) {
            //allow only letter,space and Iso control char

            txtUserName.setEditable(true);
        } else {
            JOptionPane.showMessageDialog(ManageUsersJPanel, "Username must be a String value");
            txtUserName.setEditable(false);

        }
        
    }//GEN-LAST:event_txtUserNameKeyTyped

    private void cmbRolesNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRolesNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRolesNameActionPerformed

    private void txtContactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContactKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
				if (Character.isDigit(c) || Character.isISOControl(c)) {
					txtContact.setEditable(true);
				}
				else {
					JOptionPane.showMessageDialog(this, "Contact No must be a Integer value");
					txtContact.setEditable(false);
				}
        
    }//GEN-LAST:event_txtContactKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel UserNameLb1;
    private javax.swing.JComboBox<String> cmbRolesName;
    private javax.swing.JLabel conatctLb;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel emailLb;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel mainImage1;
    private javax.swing.JLabel passwordLb;
    private javax.swing.JLabel roleNameLb;
    private javax.swing.JButton saveLb;
    private javax.swing.JTable tblPatient;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables

    private void loadUsers() {
        DefaultTableModel model = (DefaultTableModel) tblPatient.getModel();
        model.setRowCount(0);
        List<LoginDetails> findAll = loginDetailDetailRepository.findAll();
        for (LoginDetails entity : findAll) {
            Object[] data = {entity.getUsername(),
                entity.getUserPassword(),
                entity.getRoleName(),
                entity.getEmail(),
               entity.getContactNo()};
            model.addRow(data);
        }
    }
}
