/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.view;

import com.entity.EnterpriseEntity;
import com.entity.Network;
import com.entity.OrganizationEntity;
import com.repositories.EnterpriseRepository;
import com.repositories.OrganizationRepository;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.springframework.context.ApplicationContext;
import org.springframework.stereotype.Controller;

/**
 *
 * @author ajitpatil
 */
@Controller(value = "ManageEnterprisePanel")
public class ManageEnterprisePanel extends javax.swing.JPanel {

    EnterpriseRepository networkRepository;

    /**
     * Creates new form ManageOrganizationJPanel
     */
    public ManageEnterprisePanel(EnterpriseRepository networkRepository,
            ApplicationContext applicationContext) {
        this.networkRepository = applicationContext.getBean(EnterpriseRepository.class);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtOrgName = new javax.swing.JTextField();
        txtEnterpriseId = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        enterpriseIdLb = new javax.swing.JLabel();
        organizationNameLb = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        reloadBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mainImage1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtOrgName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtOrgName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtOrgNameKeyTyped(evt);
            }
        });
        add(txtOrgName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 250, 35));

        txtEnterpriseId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtEnterpriseId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEnterpriseIdKeyTyped(evt);
            }
        });
        add(txtEnterpriseId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 250, 35));

        addBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 250, 35));

        enterpriseIdLb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        enterpriseIdLb.setText("Enterprise Id");
        add(enterpriseIdLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 250, 35));

        organizationNameLb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        organizationNameLb.setText("Enterprise Name");
        add(organizationNameLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 150, 35));

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "EnterPrise Id", "EnterPrise Name"
            }
        ));
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 22, 440, 480));

        updateBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 250, 35));

        deleteBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 250, 35));

        reloadBtn.setText("Reload");
        reloadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reloadBtnActionPerformed(evt);
            }
        });
        add(reloadBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 520, -1, -1));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, -1, -1));

        mainImage1.setBackground(new java.awt.Color(41, 46, 64));
        mainImage1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        mainImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/Mentally Healthy Communities .jpg"))); // NOI18N
        mainImage1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 170, 170), 2));
        mainImage1.setMaximumSize(new java.awt.Dimension(728, 410));
        mainImage1.setMinimumSize(new java.awt.Dimension(728, 410));
        mainImage1.setOpaque(true);
        mainImage1.setPreferredSize(new java.awt.Dimension(728, 410));
        add(mainImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 700));
    }// </editor-fold>//GEN-END:initComponents

    private void txtEnterpriseIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEnterpriseIdKeyTyped

        char c = evt.getKeyChar();
        if (Character.isDigit(c) || Character.isISOControl(c)) {
            txtEnterpriseId.setEditable(true);
        } else {
            JOptionPane.showMessageDialog(this, "Enterprise Id must be a Integer value");
            txtEnterpriseId.setEditable(false);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnterpriseIdKeyTyped

    private void txtOrgNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOrgNameKeyTyped
        char c = evt.getKeyChar();
        if (Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)) {
            //allow only letter,space and Iso control char

            txtOrgName.setEditable(true);
        } else {
            JOptionPane.showMessageDialog(this, "Enterprise Name must be a String value");
            txtOrgName.setEditable(false);

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrgNameKeyTyped

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();
        if (model.getRowCount() != 0) {
            String city = model.getValueAt(tbl.getSelectedRow(), 0).toString();
            EnterpriseEntity finddetailByCity = networkRepository.finddetailByCity(Integer.parseInt(city));
            if (null != finddetailByCity) {
                jLabel1.setText(Integer.toString(finddetailByCity.getId()));
                txtEnterpriseId.setText(Integer.toString(finddetailByCity.getId()));
                txtOrgName.setText(finddetailByCity.getName());
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_tblMouseClicked

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        EnterpriseEntity network = new EnterpriseEntity();
        network.setName(txtOrgName.getText());
        network.setId(Integer.parseInt(txtEnterpriseId.getText()));
        networkRepository.save(network);
        JOptionPane.showMessageDialog(this, "Enterprise Updated");        // TODO add your handling code here:
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        if (!jLabel1.getText().equals("")) {
            networkRepository.deleteById(Integer.parseInt(jLabel1.getText()));
             JOptionPane.showMessageDialog(this, "Enterprise Deleted"); 
        } else {
            JOptionPane.showMessageDialog(this, "Please search or select record to delete");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void reloadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reloadBtnActionPerformed
        loadPatients();     // TODO add your handling code here:
    }//GEN-LAST:event_reloadBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        EnterpriseEntity network = new EnterpriseEntity();
        network.setName(txtOrgName.getText());
        network.setId(Integer.parseInt(txtEnterpriseId.getText()));
        networkRepository.save(network);
        JOptionPane.showMessageDialog(this, "EnterPrise Added");
    }//GEN-LAST:event_addBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel enterpriseIdLb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mainImage1;
    private javax.swing.JLabel organizationNameLb;
    private javax.swing.JButton reloadBtn;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txtEnterpriseId;
    private javax.swing.JTextField txtOrgName;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
private void loadPatients() {
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();
        model.setRowCount(0);
        List<EnterpriseEntity> findAll = networkRepository.findAll();
        for (EnterpriseEntity entity : findAll) {

            Object[] data = {entity.getId(),
                entity.getName()};
            model.addRow(data);

        }
    }
}
