/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view;

import com.entity.PrisonPatientDiagnoseEntity;
import com.entity.PrisonPatientEntity;
import com.entity.PrisonPatientVitalEntity;
import com.repositories.PatientRepositoryPrison;
import com.repositories.PrisonPatientDiagnoseRepository;
import com.repositories.PrisonPatientVitalRepository;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.springframework.context.ApplicationContext;
import org.springframework.stereotype.Controller;

 
@Controller(value = "PsychWardWardenPanel")
public class PsychWardWardenPanel extends javax.swing.JPanel {

    PrisonPatientDiagnoseRepository diagnoseRepository;
    PrisonPatientVitalRepository patientVitalRepository;
    PatientRepositoryPrison patientRepository;

    /**
     * Creates new form PsychWardWardenPanel
     */
    public PsychWardWardenPanel(PrisonPatientDiagnoseRepository diagnoseRepository,
            PatientRepositoryPrison patientRepository,
            PrisonPatientVitalRepository patientVitalRepository,
            ApplicationContext applicationContext) {
        this.diagnoseRepository = applicationContext.getBean(PrisonPatientDiagnoseRepository.class);
        this.patientVitalRepository = applicationContext.getBean(PrisonPatientVitalRepository.class);
        this.patientRepository = applicationContext.getBean(PatientRepositoryPrison.class);
        initComponents();
        loadPatients();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblPatient = new javax.swing.JTable();
        idLb = new javax.swing.JLabel();
        nameLb = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        admitPhyschBtn = new javax.swing.JButton();
        reloadBtn = new javax.swing.JButton();
        mainImage1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblPatient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PATIENT ID", "NAME", "PRESCRIPTION", "PATIENT STATUS", "Doctor Comments", "Legal Advisor Comments", "Police Comments"
            }
        ));
        tblPatient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPatientMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPatient);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 1010, 330));

        idLb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        idLb.setText("Id");
        add(idLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 30, 40));

        nameLb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nameLb.setText("Name");
        add(nameLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 500, 60, 40));

        txtName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 490, 280, 50));

        txtId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, 280, 50));

        admitPhyschBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        admitPhyschBtn.setText("Admit");
        admitPhyschBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admitPhyschBtnActionPerformed(evt);
            }
        });
        add(admitPhyschBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 560, 270, 40));

        reloadBtn.setText("Reload");
        reloadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reloadBtnActionPerformed(evt);
            }
        });
        add(reloadBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 410, -1, -1));

        mainImage1.setBackground(new java.awt.Color(41, 46, 64));
        mainImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/Mentally Healthy Communities .jpg"))); // NOI18N
        mainImage1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 170, 170), 2));
        mainImage1.setMaximumSize(new java.awt.Dimension(728, 410));
        mainImage1.setMinimumSize(new java.awt.Dimension(728, 410));
        mainImage1.setOpaque(true);
        mainImage1.setPreferredSize(new java.awt.Dimension(728, 410));
        add(mainImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));
    }// </editor-fold>//GEN-END:initComponents

    private void tblPatientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPatientMouseClicked
        DefaultTableModel model = (DefaultTableModel) tblPatient.getModel();
        if (model.getRowCount() != 0) {
            String id = model.getValueAt(tblPatient.getSelectedRow(), 0).toString();
            String name = model.getValueAt(tblPatient.getSelectedRow(), 1).toString();
            txtId.setText(id);
            txtName.setText(name);
        }          // TODO add your handling code here:
    }//GEN-LAST:event_tblPatientMouseClicked

    private void admitPhyschBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admitPhyschBtnActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblPatient.getModel();
        if (model.getRowCount() != 0) {
            String id = model.getValueAt(tblPatient.getSelectedRow(), 0).toString();
            PrisonPatientEntity finddetailById = patientRepository.finddetailById(Integer.parseInt(id));
            if (null != finddetailById) {
                finddetailById.setStatus("Admitted");
                PrisonPatientDiagnoseEntity finddetailById1 = diagnoseRepository.finddetailById(finddetailById.getId());
                diagnoseRepository.save(finddetailById1);
                patientRepository.save(finddetailById);
                loadPatients();
                JOptionPane.showMessageDialog(this, "Admitted to Physc Ward");
            }
        }
    }//GEN-LAST:event_admitPhyschBtnActionPerformed

    private void reloadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reloadBtnActionPerformed
        loadPatients(); // TODO add your handling code here:
    }//GEN-LAST:event_reloadBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admitPhyschBtn;
    private javax.swing.JLabel idLb;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel mainImage1;
    private javax.swing.JLabel nameLb;
    private javax.swing.JButton reloadBtn;
    private javax.swing.JTable tblPatient;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
private void loadPatients() {
        DefaultTableModel model = (DefaultTableModel) tblPatient.getModel();
        model.setRowCount(0);
        List<PrisonPatientEntity> findAll = patientRepository.findAll();
        for (PrisonPatientEntity entity : findAll) {
            if (entity.getStatus().equals("Sent to Psych Ward")) {
                PrisonPatientVitalEntity finddetailById = patientVitalRepository.finddetailById(entity.getId());
                PrisonPatientDiagnoseEntity diagnoseEntity = diagnoseRepository.finddetailById(entity.getId());
                if (null != finddetailById) {
                    Object[] data = {entity.getId(),
                        entity.getName(),
                        diagnoseEntity.getPrescription(),
                        entity.getStatus(),
                        diagnoseEntity.getComments(),
                        diagnoseEntity.getCommelegalAdvisorComments(),
                        diagnoseEntity.getPoliceComments()};

                    model.addRow(data);
                }
            }

        }
    }
}
