/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view;

import com.entity.LoginDetails;
import com.repositories.LoginDetailDetailRepository;
import com.util.MailUtils;

import com.util.EmailValidator;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.springframework.context.ApplicationContext;
import org.springframework.stereotype.Controller;

@Controller(value = "SignUp")
public class SignUp extends javax.swing.JFrame {

    private JFrame SignUp;

    private LoginDetailDetailRepository loginDetailDetailRepository;

    /**
     * Creates new form SignUp
     */
    public SignUp(
            LoginDetailDetailRepository loginDetailDetailRepository,
            ApplicationContext applicationContext) {
        this.loginDetailDetailRepository = applicationContext.getBean(LoginDetailDetailRepository.class);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUserName = new javax.swing.JTextField();
        txtUserPassword = new javax.swing.JPasswordField();
        txtConfirmPassword = new javax.swing.JPasswordField();
        cmbRole = new javax.swing.JComboBox<>();
        txtEmail = new javax.swing.JTextField();
        txtContactNo = new javax.swing.JTextField();
        loginBtn = new javax.swing.JButton();
        signUpBtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        contactLb = new javax.swing.JLabel();
        userNameLb = new javax.swing.JLabel();
        userPasswordLb = new javax.swing.JLabel();
        userConfirmPasswordLb = new javax.swing.JLabel();
        roleNameLb = new javax.swing.JLabel();
        emailLb = new javax.swing.JLabel();
        mainImage1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUserName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUserNameKeyTyped(evt);
            }
        });
        getContentPane().add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 380, 35));

        txtUserPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtUserPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 380, 35));

        txtConfirmPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 380, 35));

        cmbRole.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PATIENT", "COUNSELOR", "DOCTOR", "PHARMACY", "REHAB", "JAILADMIN", "LEGAL ADVISOR", "POLICE", "PSYCH WARD", "SYSTEMADMIN", "PATIENTENTADMIN", "HOSPITALENTADMIN", "JUSTICEENTADMIN", "PHSYCENTADMIN", " " }));
        getContentPane().add(cmbRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 380, 35));

        txtEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmailKeyTyped(evt);
            }
        });
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 450, 380, 35));

        txtContactNo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtContactNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContactNoKeyTyped(evt);
            }
        });
        getContentPane().add(txtContactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 530, 380, 35));

        loginBtn.setBackground(new java.awt.Color(51, 51, 51));
        loginBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 0, 204));
        loginBtn.setText("Go to Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        getContentPane().add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 640, 380, 30));

        signUpBtn.setBackground(new java.awt.Color(51, 51, 51));
        signUpBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        signUpBtn.setForeground(new java.awt.Color(255, 0, 204));
        signUpBtn.setText("Sign Up");
        signUpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpBtnActionPerformed(evt);
            }
        });
        getContentPane().add(signUpBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 590, 380, 30));

        jButton3.setText("Sign Up");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 590, 380, 30));

        jButton5.setBackground(new java.awt.Color(255, 0, 0));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("CLOSE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 10, 200, 40));

        contactLb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        contactLb.setForeground(new java.awt.Color(51, 51, 51));
        contactLb.setText("Contact No");
        getContentPane().add(contactLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 490, 380, 40));

        userNameLb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        userNameLb.setForeground(new java.awt.Color(51, 51, 51));
        userNameLb.setText("User Name");
        getContentPane().add(userNameLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 380, 40));

        userPasswordLb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        userPasswordLb.setForeground(new java.awt.Color(51, 51, 51));
        userPasswordLb.setText("User Password");
        getContentPane().add(userPasswordLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 380, 40));

        userConfirmPasswordLb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        userConfirmPasswordLb.setForeground(new java.awt.Color(51, 51, 51));
        userConfirmPasswordLb.setText("Confirm Password");
        getContentPane().add(userConfirmPasswordLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 380, 40));

        roleNameLb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        roleNameLb.setForeground(new java.awt.Color(51, 51, 51));
        roleNameLb.setText("Role Name");
        getContentPane().add(roleNameLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 380, 40));

        emailLb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        emailLb.setForeground(new java.awt.Color(51, 51, 51));
        emailLb.setText("Email");
        getContentPane().add(emailLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, 380, 40));

        mainImage1.setBackground(new java.awt.Color(41, 46, 64));
        mainImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/Mentally Healthy Communities .jpg"))); // NOI18N
        mainImage1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 170, 170), 2));
        mainImage1.setMaximumSize(new java.awt.Dimension(728, 410));
        mainImage1.setMinimumSize(new java.awt.Dimension(728, 410));
        mainImage1.setOpaque(true);
        mainImage1.setPreferredSize(new java.awt.Dimension(728, 410));
        getContentPane().add(mainImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_loginBtnActionPerformed

    private void signUpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpBtnActionPerformed
        EmailValidator emailValidator = new EmailValidator();
        boolean flag = ContactNoValidation();
        
        if (!emailValidator.validate(txtEmail.getText().trim())) {
            JOptionPane.showMessageDialog(this, "Invalid Email !!");

        } 
        
       if (flag==false){
             JOptionPane.showMessageDialog(this, "Invalid Contact No !!");
       }
       
        else{
           
           
            saveUser();
            
            
            
            String userName= txtUserName.getText();
            MailUtils.sendEmail(txtEmail.getText(), "Sign up !!", userName +" " +"Signup Successfully");
        txtUserName.setText("");
        txtUserPassword.setText("");
        txtConfirmPassword.setText("");
        txtEmail.setText("");
        txtContactNo.setText("");
       
       
       }

    }//GEN-LAST:event_signUpBtnActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtUserNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserNameKeyTyped
        // TODO add your handling code here:

        char c = evt.getKeyChar();
        if (Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)) {
            //allow only letter,space and Iso control char

            txtUserName.setEditable(true);
        } else {
            JOptionPane.showMessageDialog(SignUp, "Username must be a String value");
            txtUserName.setEditable(false);

        }

    }//GEN-LAST:event_txtUserNameKeyTyped

    private void txtEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtEmailKeyTyped

    private void txtContactNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContactNoKeyTyped
        // TODO add your handling code here:
        	char c = evt.getKeyChar();
				if (Character.isDigit(c) || Character.isISOControl(c)) {
					txtContactNo.setEditable(true);
				}
				else {
					JOptionPane.showMessageDialog(SignUp, "Contact No must be a Integer value");
					txtContactNo.setEditable(false);
				}
    }//GEN-LAST:event_txtContactNoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JLabel contactLb;
    private javax.swing.JLabel emailLb;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel mainImage1;
    private javax.swing.JLabel roleNameLb;
    private javax.swing.JButton signUpBtn;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JTextField txtContactNo;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JPasswordField txtUserPassword;
    private javax.swing.JLabel userConfirmPasswordLb;
    private javax.swing.JLabel userNameLb;
    private javax.swing.JLabel userPasswordLb;
    // End of variables declaration//GEN-END:variables

    private void saveUser() {
        try {
            String userName = txtUserName.getText();
            String password = txtUserPassword.getText();
            String confirmPassword = txtConfirmPassword.getText();
            String contact = txtContactNo.getText();
            String email = txtEmail.getText();
            String role = cmbRole.getSelectedItem().toString();
            if (!password.equals(confirmPassword)) {
                JOptionPane.showMessageDialog(this, "Password mismatch !!");
            } 
            
            else {
                
                LoginDetails details = new LoginDetails();
                details.setContactNo(contact);
                details.setEmail(email);
                details.setId(null);
                details.setName(userName);
                details.setUsername(userName);
                details.setUserPassword(password);
                details.setRoleName(role);
                loginDetailDetailRepository.save(details);
                JOptionPane.showMessageDialog(this, "User Registered Successfully !!");
                this.dispose();
            }
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Failed !!");
        }
    }
    
    private boolean ContactNoValidation(){
        try{
            
            String contactNo = txtContactNo.getText();
            Pattern ptrn = Pattern.compile("(0/91)?[7-9][0-9]{9}");  
            Matcher match = ptrn.matcher(contactNo); 
            return(match.find() && match.group().equals(contactNo));    
        }
        
        catch(Exception e) {
         return false;
        }

}

}
