/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.view;

 
import org.springframework.context.ApplicationContext;
import org.springframework.stereotype.Controller;

/**
 *
 * @author ajitpatil
 */
@Controller(value = "SystemAdminJFrame")
public class SystemAdminJFrame extends javax.swing.JFrame {

    NetworkJPanel networkJPanel;
    ManageEnterprisePanel manageEnterpriseJPanel;
    ManageOrganizationJPanel manageOrganizationJPanel;
    ManageUsersJPanel manageUsersJPanel;
    //private JFrame  LoginPage ;

    /**
     * Creates new form SystemAdminJFrame
     */
    
            
    public SystemAdminJFrame(ManageUsersJPanel manageUsersJPanel,
            ManageOrganizationJPanel manageOrganizationJPanel,
            ManageEnterprisePanel manageEnterpriseJPanel,
            NetworkJPanel networkJPanel,
            ApplicationContext applicationContext) {
        this.manageUsersJPanel = applicationContext.getBean(ManageUsersJPanel.class);
        this.manageOrganizationJPanel = applicationContext.getBean(ManageOrganizationJPanel.class);
        this.manageEnterpriseJPanel = applicationContext.getBean(ManageEnterprisePanel.class);
        this.networkJPanel = applicationContext.getBean(NetworkJPanel.class);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane = new javax.swing.JSplitPane();
        systemAdminLeftJPanel = new javax.swing.JPanel();
        enterpriseManageBtn = new javax.swing.JButton();
        userManageBtn = new javax.swing.JButton();
        organizationManageBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        ManageNetworkBtn = new javax.swing.JButton();
        panelMain = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        systemAdminLeftJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enterpriseManageBtn.setText("Manage EnterPrises");
        enterpriseManageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterpriseManageBtnActionPerformed(evt);
            }
        });
        systemAdminLeftJPanel.add(enterpriseManageBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 150, -1));

        userManageBtn.setText("Manage Users");
        userManageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userManageBtnActionPerformed(evt);
            }
        });
        systemAdminLeftJPanel.add(userManageBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 150, -1));

        organizationManageBtn.setText("Manage Organization");
        organizationManageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizationManageBtnActionPerformed(evt);
            }
        });
        systemAdminLeftJPanel.add(organizationManageBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 150, -1));

        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        systemAdminLeftJPanel.add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 140, -1));

        ManageNetworkBtn.setText("Manage Network");
        ManageNetworkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageNetworkBtnActionPerformed(evt);
            }
        });
        systemAdminLeftJPanel.add(ManageNetworkBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 150, -1));

        jSplitPane.setLeftComponent(systemAdminLeftJPanel);

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 949, Short.MAX_VALUE)
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 665, Short.MAX_VALUE)
        );

        jSplitPane.setRightComponent(panelMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1112, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userManageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userManageBtnActionPerformed
        panelMain.removeAll();
        manageUsersJPanel.setSize(panelMain.getSize());
        panelMain.add(manageUsersJPanel);
        panelMain.repaint();
        panelMain.revalidate();
    }//GEN-LAST:event_userManageBtnActionPerformed

    private void enterpriseManageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterpriseManageBtnActionPerformed
        // TODO add your handling code here:
        panelMain.removeAll();
        manageEnterpriseJPanel.setSize(panelMain.getSize());
        panelMain.add(manageEnterpriseJPanel);
        panelMain.repaint();
        panelMain.revalidate();
    }//GEN-LAST:event_enterpriseManageBtnActionPerformed

    private void organizationManageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationManageBtnActionPerformed
        panelMain.removeAll();
        manageOrganizationJPanel.setSize(panelMain.getSize());
        panelMain.add(manageOrganizationJPanel);
        panelMain.repaint();
        panelMain.revalidate();
    }//GEN-LAST:event_organizationManageBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
      this.dispose();

    }//GEN-LAST:event_logoutBtnActionPerformed

    private void ManageNetworkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageNetworkBtnActionPerformed
        panelMain.removeAll();
        networkJPanel.setSize(panelMain.getSize());
        panelMain.add(networkJPanel);
        panelMain.repaint();
        panelMain.revalidate();
    }//GEN-LAST:event_ManageNetworkBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SystemAdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SystemAdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SystemAdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SystemAdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ManageNetworkBtn;
    private javax.swing.JButton enterpriseManageBtn;
    private javax.swing.JSplitPane jSplitPane;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton organizationManageBtn;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel systemAdminLeftJPanel;
    private javax.swing.JButton userManageBtn;
    // End of variables declaration//GEN-END:variables
}
