/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view;

import com.entity.PatientEntity;
import com.entity.PatientVitalEntity;
import com.repositories.PatientRepository;
import com.repositories.PatientVitalRepository;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.springframework.context.ApplicationContext;
import org.springframework.stereotype.Controller;

@Controller(value = "ViewPatientPanel")
public class ViewPatientPanel extends javax.swing.JPanel {
private JPanel ViewPatientPanel;
    PatientRepository patientRepository;
    PatientVitalRepository patientVitalRepository;

    /**
     * Creates new form ViewPatientPanel
     */
    public ViewPatientPanel(PatientVitalRepository patientVitalRepository,
            PatientRepository patientRepository,
            ApplicationContext applicationContext) {
        this.patientVitalRepository = applicationContext.getBean(PatientVitalRepository.class);
        this.patientRepository = applicationContext.getBean(PatientRepository.class);
        initComponents();
        loadPatients();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl1 = new javax.swing.JTable();
        gad7scoreLb = new javax.swing.JLabel();
        patientIDLb = new javax.swing.JLabel();
        patientNameLb = new javax.swing.JLabel();
        bpLb = new javax.swing.JLabel();
        weightLb = new javax.swing.JLabel();
        phq9scoreLb = new javax.swing.JLabel();
        sendtoDocBtn = new javax.swing.JButton();
        savevitalBtn = new javax.swing.JButton();
        phq9Combo = new javax.swing.JComboBox<>();
        gad7Combobox = new javax.swing.JComboBox<>();
        txtBp = new javax.swing.JTextField();
        txtWeight = new javax.swing.JTextField();
        txtPatientId = new javax.swing.JTextField();
        txtPatientName = new javax.swing.JTextField();
        reloadBtn = new javax.swing.JButton();
        mainImage1 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PATIENT ID", "PATIENT NAME", "PATIENT CONCERN", "PATIENT STATUS"
            }
        ));
        tbl1.setRowHeight(30);
        tbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 990, 330));

        gad7scoreLb.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        gad7scoreLb.setText("GAD-7 SCORE");
        add(gad7scoreLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 570, 120, 35));

        patientIDLb.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        patientIDLb.setText("PATIENT ID");
        add(patientIDLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 110, 35));

        patientNameLb.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        patientNameLb.setText("PATIENT NAME");
        add(patientNameLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 120, 35));

        bpLb.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        bpLb.setText("BLOODPRESSURE");
        add(bpLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 450, 130, 35));

        weightLb.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        weightLb.setText("WEIGHT");
        add(weightLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 490, 120, 35));

        phq9scoreLb.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        phq9scoreLb.setText("PHQ-9 SCORE");
        add(phq9scoreLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 530, 120, 35));

        sendtoDocBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        sendtoDocBtn.setText("SEND DETAILS TO DOCTOR");
        sendtoDocBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendtoDocBtnActionPerformed(evt);
            }
        });
        add(sendtoDocBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 620, 280, 35));

        savevitalBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        savevitalBtn.setText("SAVE");
        savevitalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savevitalBtnActionPerformed(evt);
            }
        });
        add(savevitalBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 620, -1, 35));

        phq9Combo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        phq9Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27" }));
        add(phq9Combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 540, 360, -1));

        gad7Combobox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gad7Combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", " " }));
        add(gad7Combobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 580, 360, -1));

        txtBp.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtBp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBpKeyTyped(evt);
            }
        });
        add(txtBp, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, 360, 35));

        txtWeight.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtWeight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtWeightKeyTyped(evt);
            }
        });
        add(txtWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, 360, 35));

        txtPatientId.setEditable(false);
        txtPatientId.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        add(txtPatientId, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 360, 35));

        txtPatientName.setEditable(false);
        txtPatientName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        add(txtPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, 360, 35));

        reloadBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reloadBtn.setText("Reload");
        reloadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reloadBtnActionPerformed(evt);
            }
        });
        add(reloadBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(935, 360, 90, -1));

        mainImage1.setBackground(new java.awt.Color(41, 46, 64));
        mainImage1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        mainImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/Mentally Healthy Communities .jpg"))); // NOI18N
        mainImage1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 170, 170), 2));
        mainImage1.setMaximumSize(new java.awt.Dimension(728, 410));
        mainImage1.setMinimumSize(new java.awt.Dimension(728, 410));
        mainImage1.setOpaque(true);
        mainImage1.setPreferredSize(new java.awt.Dimension(728, 410));
        add(mainImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 700));
    }// </editor-fold>//GEN-END:initComponents

    private void tbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl1MouseClicked
        DefaultTableModel model = (DefaultTableModel) tbl1.getModel();
        if (model.getRowCount() != 0) {
            String id = model.getValueAt(tbl1.getSelectedRow(), 0).toString();
            String name = model.getValueAt(tbl1.getSelectedRow(), 1).toString();
            txtPatientId.setText(id);
            txtPatientName.setText(name);

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl1MouseClicked

    private void reloadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reloadBtnActionPerformed
        loadPatients();        // TODO add your handling code here:
    }//GEN-LAST:event_reloadBtnActionPerformed

    private void sendtoDocBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendtoDocBtnActionPerformed
        try {
            PatientEntity patientEntity = patientRepository.finddetailById(Integer.parseInt(txtPatientId.getText()));
            patientEntity.setId(Integer.parseInt(txtPatientId.getText()));
            patientEntity.setStatus("Sent to Doctor");
            patientRepository.save(patientEntity);
            JOptionPane.showMessageDialog(this, "Patient Details sent to Doctor");
            
            txtPatientId.setText("");
            txtBp.setText("");
            //txtGad.setText("");
            txtWeight.setText("");
           // txtPhq.setText("");
            txtPatientName.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Failed");
        }
    }//GEN-LAST:event_sendtoDocBtnActionPerformed

    private void savevitalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savevitalBtnActionPerformed
        try {
            PatientVitalEntity entity = new PatientVitalEntity();
            entity.setId(null);
            entity.setBp(Double.parseDouble(txtBp.getText()));
            entity.setGad(Integer.parseInt(gad7Combobox.getSelectedItem().toString()));
            entity.setWeight(Integer.parseInt(txtWeight.getText()));
            entity.setPhq(Integer.parseInt(phq9Combo.getSelectedItem().toString()));
            entity.setPatientId(Integer.parseInt(txtPatientId.getText()));
            patientVitalRepository.save(entity);
            JOptionPane.showMessageDialog(this, "Saved Vital Info");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Failed");
        }
    }//GEN-LAST:event_savevitalBtnActionPerformed

    private void txtBpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBpKeyTyped
        // TODO add your handling code here:
        
        char c = evt.getKeyChar();
				if (Character.isDigit(c) || Character.isISOControl(c)) {
					txtBp.setEditable(true);
				}
				else {
					JOptionPane.showMessageDialog(ViewPatientPanel, "Blood Pressure must be a Integer value");
					txtBp.setEditable(false);
				}
    }//GEN-LAST:event_txtBpKeyTyped

    private void txtWeightKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWeightKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
				if (Character.isDigit(c) || Character.isISOControl(c)) {
					txtWeight.setEditable(true);
				}
				else {
					JOptionPane.showMessageDialog(ViewPatientPanel, "Weight must be a Integer value");
					txtWeight.setEditable(false);
				}   
        
    }//GEN-LAST:event_txtWeightKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bpLb;
    private javax.swing.JComboBox<String> gad7Combobox;
    private javax.swing.JLabel gad7scoreLb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mainImage1;
    private javax.swing.JLabel patientIDLb;
    private javax.swing.JLabel patientNameLb;
    private javax.swing.JComboBox<String> phq9Combo;
    private javax.swing.JLabel phq9scoreLb;
    private javax.swing.JButton reloadBtn;
    private javax.swing.JButton savevitalBtn;
    private javax.swing.JButton sendtoDocBtn;
    private javax.swing.JTable tbl1;
    private javax.swing.JTextField txtBp;
    private javax.swing.JTextField txtPatientId;
    private javax.swing.JTextField txtPatientName;
    private javax.swing.JTextField txtWeight;
    private javax.swing.JLabel weightLb;
    // End of variables declaration//GEN-END:variables

    private void loadPatients() {
        DefaultTableModel model = (DefaultTableModel) tbl1.getModel();
        model.setRowCount(0);
        List<PatientEntity> findAll = patientRepository.findAll();
        for (PatientEntity entity : findAll) {
            if (entity.getStatus().equals("PENDING")) {
                Object[] data = {entity.getId(),
                    entity.getName(), entity.getConcern(), entity.getStatus()};

                model.addRow(data);
            }

        }
    }
}
